<h1 class="mx-auto" style="width: 300px;">Clube Do GTA</h1>
	
	<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <a class="nav-link active" href="#">Ativo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Link nav muito mais longo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Desativado</a>
  </li>
</ul>




<nav class="nav nav-pills nav-justified justify-content-center">
  <a class="nav-item nav-link active" href="#">Ativo</a>
  <a class="nav-item nav-link" href="#">Link</a>
  <a class="nav-item nav-link" href="#">Link</a>
  <a class="nav-item nav-link disabled" href="#">Desativado</a>
</nav>







<nav class="nav nav-pills flex-column flex-sm-row justify-content-center">
  <a class="flex-sm-fill text-sm-center nav-link active" href="#">Ativo</a>
  <a class="flex-sm-fill text-sm-center nav-link" href="#">Link</a>
  <a class="flex-sm-fill text-sm-center nav-link" href="#">Link</a>
  <a class="flex-sm-fill text-sm-center nav-link disabled" href="#">Desativado</a>
</nav>

<ul class="nav nav-tabs justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="#">Ativo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Desativado</a>
  </li>
</ul>

<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="#">Ativo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Desativado</a>
  </li>
</ul>

<ul class="nav justify-content-center bg-light">
  <li class="nav-item">
    <a class="nav-link active" href="#">Ativo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Desativado</a>
  </li>
</ul>
	
	<span class="d-block p-2 bg-secondary">
		<div class="mx-auto" style="width: 300px;">
			<div class="d-inline p-2 m-2 bg-primary text-white">link1</div>
		  
			<div class="d-inline p-2 bg-dark text-white">link2</div>
		</div>
	</span>