<div class="bg-primary border border-light">
	<h1 class="mx-auto text-light " style="width: 500px;">Clube Do GTA</h1>
	<ul class="nav nav-tabs pb-1 bg-dark justify-content-center ">
	  <li class="nav-item">
		<a class="nav-link bg-dark text-light" href="#">Home</a>
	  </li>
	  <li class="nav-item">
		<a class="nav-link bg-dark text-light" href="#">Link</a>
	  </li>
	  <li class="nav-item">
		<a class="nav-link bg-dark text-light" href="#">Link</a>
	  </li>
	  <li class="nav-item">
		<a class="nav-link bg-dark text-light" href="#">Desativado</a>
	  </li>
	</ul>
</div>

